---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.nameOverride | default (printf "%s-secret" .Release.Name) }}
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  connection:
      {{- $files := .Files }}
      {{- if .Values.fileLit }}
      {{- range $key, $val := .Values.fileLit }}
      {{ $key }}: {{ $files.Get $val | b64enc }}
      {{- end }}
      {{- end }}
      {{- if .Values.dirglob }}
      {{- range $path, $bytes := $files.Glob .Values.dirglob }}
      {{ $path }}: '{{ $files.Get $path | b64enc }}'
      {{- end }}
      {{- end }}
      {{- if .Values.seclit }}
      {{- range $key, $val := .Values.seclit }}
      {{ $key }}: {{ $val }}
      {{- end }}
      {{- end }}
